import fs from 'node:fs';import assert from 'node:assert/strict';import {connect,wait} from './cdp.mjs';
const base=process.env.PIG_PWA_TEST_URL||'http://127.0.0.1:8768',p=await connect(),report={};
const until=async(fn,message,ms=20000)=>{const start=Date.now();while(Date.now()-start<ms){if(await fn())return;await wait(100)}throw Error(message)};
const navigate=async url=>{await p.send('Page.navigate',{url});await wait(500)};
async function dismiss(){for(let i=0;i<25;i++){if(await p.evaluate(`document.querySelector('#dialogue').classList.contains('hidden')`))return;await p.evaluate(`document.querySelector('#dialogue').click()`);await wait(70)}}
await p.send('Network.enable');await p.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await p.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});
const tabs=await fetch('http://127.0.0.1:'+Number(process.env.TUN_CDP_PORT||9266)+'/json/list').then(r=>r.json());for(const tab of tabs)if(tab.id!==p.targetId&&tab.url.startsWith(base))await p.send('Target.closeTarget',{targetId:tab.id});
await navigate(base+'/asset-manifest.json');await p.evaluate(`(async()=>{for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();for(const key of await caches.keys())await caches.delete(key);localStorage.clear()})()`);await navigate('about:blank');await navigate(base);p.errors.length=0;
await until(()=>p.evaluate(`window.PocketPWA?.getStatus().offlineReady&&!!navigator.serviceWorker.controller`),'Offline download did not complete');
const asset=JSON.parse(fs.readFileSync(new URL('../dist/asset-manifest.json',import.meta.url)));report.install=await p.evaluate(`(async()=>{const names=await caches.keys(),cache=await caches.open(names.find(n=>n.startsWith('tun-story-release-')));return{cacheNames:names,count:(await cache.keys()).length,status:document.querySelector('#pwa-status').textContent}})()`);assert.equal(report.install.count,asset.files.length);
await p.evaluate(`document.querySelector('#install-app-btn').click()`);await wait(120);assert(await p.evaluate(`!document.querySelector('#install-help').classList.contains('hidden')`));await p.screenshot(new URL('../qa/install-portrait.png',import.meta.url));
await p.send('Emulation.setDeviceMetricsOverride',{width:844,height:390,deviceScaleFactor:1,mobile:true});await wait(200);await p.screenshot(new URL('../qa/install-landscape.png',import.meta.url));const bounds=await p.evaluate(`(()=>{const r=document.querySelector('.pwa-help-card').getBoundingClientRect();return{top:r.top,bottom:r.bottom,height:innerHeight}})()`);assert(bounds.top>=0&&bounds.bottom<=bounds.height+1);await p.evaluate(`document.querySelector('.pwa-help-done').click()`);
await p.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await p.evaluate(`localStorage.setItem('pigFarmStory_prefs_v1',JSON.stringify({music:false,sfx:false,volume:0}));document.querySelector('#new-game-btn').click();document.querySelector('#player-name-input').value='手机测试';document.querySelector('#farm-name-input').value='随身猪场';document.querySelector('#new-save-form').requestSubmit()`);await wait(550);await dismiss();
assert.equal(await p.evaluate(`GamePlatform.getVersion()`),'1.13.0');
await p.evaluate(`document.querySelector('[data-open="pigs"]').click()`);await wait(80);const feedTab=await p.evaluate(`([...document.querySelectorAll('#panel-tabs button')].find(x=>x.textContent.includes('喂'))?.dataset.tab)`);await p.evaluate(`document.querySelector('[data-tab="${feedTab}"]').click()`);await wait(80);
const pre=await p.evaluate(`({state:GamePlatform.getState(),nodes:[...document.querySelectorAll('#pig-layer .pig-sprite')].length})`);await p.evaluate(`document.querySelector('[data-action="feed-pig"]').click()`);await wait(100);const fed=await p.evaluate(`GamePlatform.getState()`);assert(fed.pigs[0].hunger>=pre.state.pigs[0].hunger);assert(fed.inventory.feeds.basic<pre.state.inventory.feeds.basic||fed.inventory.feeds.balanced<pre.state.inventory.feeds.balanced||JSON.stringify(fed.inventory.feeds)!==JSON.stringify(pre.state.inventory.feeds));
await p.evaluate(`document.querySelector('[data-close="panel"]').click();GamePlatform.save()`);report.saved={id:fed.id,farmName:fed.farmName,quarter:fed.quarter};
await p.send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await p.send('Network.setBypassServiceWorker',{bypass:false});await p.send('Page.reload');await wait(650);
assert(await p.evaluate(`!!window.GamePlatform&&!!window.PocketPWA`));await p.evaluate(`document.querySelector('#continue-btn').click()`);await wait(300);await dismiss();const recovered=await p.evaluate(`GamePlatform.getState()`);assert.equal(recovered.id,fed.id);assert.equal(recovered.quarter,fed.quarter);assert.deepEqual(recovered.inventory,fed.inventory);
report.offline={sameSave:true,assets:await p.evaluate(`Promise.all(${JSON.stringify(asset.files)}.map(async f=>({f,ok:(await fetch(f)).ok}))).then(a=>({total:a.length,all:a.every(x=>x.ok)}))`)};assert(report.offline.assets.all);
await p.evaluate(`document.querySelector('[data-open="catalog"]').click()`);await wait(120);assert.equal(await p.evaluate(`document.querySelectorAll('.breed-portrait').length`),28);await p.screenshot(new URL('../qa/offline-catalog.png',import.meta.url));await p.evaluate(`document.querySelector('[data-close="panel"]').click()`);
// Every destination can start from the same save with no network resources available.
report.offline.maps=[];
for(const location of ['farm','market','rival','forest','village','contest']){
 await p.evaluate(`(()=>{document.querySelector('#home-btn').click();document.querySelector('#confirm-ok').click();const s=JSON.parse(localStorage.getItem('pigFarmStory_saves_v3'))[0];s.location='${location}';s.pendingEvent=null;s.nextEventIn=999;localStorage.setItem('pigFarmStory_saves_v3',JSON.stringify([s]));})()`);await p.send('Page.reload');await wait(450);await p.evaluate(`document.querySelector('#continue-btn').click()`);await wait(180);await dismiss();await until(()=>p.evaluate(`FarmArt.ready()`),'Map art unavailable offline');assert.equal(await p.evaluate(`GamePlatform.getStatus().location`),location);report.offline.maps.push(location);
}
await p.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
await p.evaluate(`document.querySelector('#home-btn').click();document.querySelector('#confirm-ok').click()`);await wait(100);
const beforeUpdate=await p.evaluate(`JSON.parse(localStorage.getItem('pigFarmStory_saves_v3'))`),originalSW=fs.readFileSync(new URL('../dist/sw.js',import.meta.url),'utf8');
fs.writeFileSync(new URL('../dist/sw-qa-update.js',import.meta.url),originalSW.replace(asset.build,asset.build+'-qa-update'));
await p.evaluate(`navigator.serviceWorker.register('./sw-qa-update.js',{scope:'./',updateViaCache:'none'})`);
await until(()=>p.evaluate(`PocketPWA.getStatus().hasUpdate&&!document.querySelector('#pwa-update').classList.contains('hidden')`),'Update did not wait for user');
const updateBounds=await p.evaluate(`(()=>{const r=document.querySelector('#pwa-update').getBoundingClientRect(),top=document.querySelector('.topbar').getBoundingClientRect();return{parent:document.querySelector('#pwa-update').parentElement.className,top:r.top}})()`);assert(updateBounds.parent.includes('title-card'));
await p.evaluate(`document.querySelector('#pwa-update-now').click()`);await until(()=>p.evaluate(`window.PocketPWA&&navigator.serviceWorker.controller?.scriptURL.includes('sw-qa-update.js')`),'Update did not activate');await wait(400);
const afterUpdate=await p.evaluate(`JSON.parse(localStorage.getItem('pigFarmStory_saves_v3'))`);assert.deepEqual(afterUpdate,beforeUpdate);report.update={saveUnchanged:true,requiresUserAction:true};
assert.deepEqual(p.errors,[]);report.errors=p.errors;report.status='PASS';fs.writeFileSync(new URL('../qa/pwa-report.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,install:{...report.install,cacheNames:report.install.cacheNames.length}},null,2));fs.rmSync(new URL('../dist/sw-qa-update.js',import.meta.url),{force:true});p.close();
